<?php
use App\Models\InvestmentCategory;

$data = [
    'Tabungan Berjangka' => [
        'description' => "Tabungan berjangka merupakan produk simpanan yang mengharuskan nasabah menyetorkan sejumlah dana secara rutin dalam jangka waktu tertentu sesuai kesepakatan dengan bank. Berbeda dengan tabungan biasa yang memungkinkan penarikan dana kapan saja, tabungan berjangka memiliki batasan penarikan sehingga membantu nasabah lebih disiplin dalam menabung. Produk ini sering dipilih oleh masyarakat yang memiliki tujuan keuangan tertentu, seperti biaya pendidikan, dana pernikahan, pembelian kendaraan, atau persiapan dana darurat. Dengan sistem setoran otomatis setiap bulan, nasabah dapat membangun kebiasaan menabung secara konsisten tanpa harus khawatir lupa menyisihkan uang.\n\nSalah satu keunggulan utama tabungan berjangka adalah tingkat keamanan yang tinggi karena dikelola oleh lembaga perbankan yang diawasi oleh otoritas keuangan. Selain itu, suku bunga yang ditawarkan biasanya lebih tinggi dibandingkan tabungan reguler, sehingga dana yang disimpan dapat berkembang lebih optimal. Beberapa bank juga menyediakan fasilitas perlindungan asuransi jiwa bagi nasabah tabungan berjangka tanpa biaya tambahan. Hal ini memberikan nilai tambah karena apabila terjadi risiko tertentu kepada nasabah, target tabungan tetap dapat tercapai sesuai ketentuan yang berlaku.\n\nMeskipun relatif aman, tabungan berjangka memiliki beberapa keterbatasan yang perlu dipertimbangkan. Dana yang tersimpan tidak dapat dicairkan secara bebas sebelum jatuh tempo tanpa dikenakan penalti atau biaya tertentu. Selain itu, tingkat keuntungan yang diperoleh masih tergolong rendah jika dibandingkan dengan instrumen investasi seperti saham atau reksa dana. Oleh karena itu, tabungan berjangka lebih cocok bagi individu yang mengutamakan keamanan dana dan memiliki tujuan keuangan jangka pendek hingga menengah daripada mengejar keuntungan investasi yang tinggi.",
        'icon' => 'piggy-bank',
        'badge' => 'RISIKO RENDAH'
    ],
    'Saham' => [
        'description' => "Saham adalah instrumen investasi yang menunjukkan kepemilikan seseorang terhadap suatu perusahaan. Ketika seseorang membeli saham, maka ia menjadi salah satu pemilik perusahaan sesuai dengan jumlah saham yang dimiliki. Investor saham memiliki peluang memperoleh keuntungan melalui kenaikan harga saham (capital gain) maupun pembagian laba perusahaan dalam bentuk dividen. Saham diperdagangkan di pasar modal melalui bursa efek, sehingga harga saham dapat berubah setiap saat mengikuti kondisi perusahaan, kinerja bisnis, sentimen pasar, serta faktor ekonomi dan politik.\n\nInvestasi saham dikenal memiliki potensi keuntungan yang tinggi dibandingkan banyak instrumen investasi lainnya. Dalam jangka panjang, saham dari perusahaan yang memiliki fundamental kuat dapat memberikan pertumbuhan nilai investasi yang signifikan. Selain itu, investor juga memiliki kesempatan untuk berpartisipasi dalam perkembangan perusahaan yang mereka pilih. Dengan kemajuan teknologi, investasi saham kini semakin mudah dilakukan melalui aplikasi sekuritas yang memungkinkan transaksi secara online dengan modal yang relatif terjangkau.\n\nDi sisi lain, saham juga memiliki tingkat risiko yang cukup tinggi karena harga saham dapat berfluktuasi secara drastis dalam waktu singkat. Investor dapat mengalami kerugian apabila harga saham turun di bawah harga beli. Oleh sebab itu, investasi saham memerlukan pemahaman yang baik mengenai analisis perusahaan, kondisi pasar, serta strategi pengelolaan risiko. Investor disarankan untuk melakukan diversifikasi portofolio dan memiliki orientasi investasi jangka panjang agar dapat mengurangi dampak volatilitas pasar yang terjadi.",
        'icon' => 'trending-up',
        'badge' => 'POPULER'
    ],
    'Reksa Dana' => [
        'description' => "Reksa dana merupakan wadah investasi yang menghimpun dana dari banyak investor untuk kemudian dikelola oleh manajer investasi ke dalam berbagai instrumen keuangan seperti saham, obligasi, dan pasar uang. Dengan sistem ini, investor tidak perlu melakukan analisis dan pengelolaan investasi secara langsung karena seluruh proses pengelolaan dilakukan oleh tenaga profesional yang memiliki pengalaman di bidang pasar modal. Reksa dana menjadi pilihan populer bagi pemula karena proses investasinya relatif mudah dan dapat dimulai dengan modal yang cukup kecil.\n\nTerdapat beberapa jenis reksa dana yang dapat dipilih sesuai tujuan dan profil risiko investor. Reksa dana pasar uang cenderung memiliki risiko paling rendah dan cocok untuk tujuan jangka pendek. Reksa dana pendapatan tetap berfokus pada obligasi sehingga menawarkan potensi keuntungan yang lebih tinggi dengan risiko menengah. Reksa dana saham memiliki potensi imbal hasil terbesar karena sebagian besar dana ditempatkan pada saham, namun tingkat risikonya juga lebih tinggi. Selain itu, terdapat reksa dana campuran yang mengombinasikan beberapa instrumen investasi dalam satu portofolio.\n\nMeskipun memberikan kemudahan dan diversifikasi investasi, reksa dana tetap memiliki risiko yang perlu dipahami oleh investor. Nilai investasi dapat naik maupun turun tergantung pada kondisi pasar dan kinerja aset yang menjadi portofolio reksa dana tersebut. Oleh karena itu, investor perlu memilih jenis reksa dana yang sesuai dengan tujuan keuangan, jangka waktu investasi, dan toleransi risiko yang dimiliki. Dengan pemilihan yang tepat dan investasi secara konsisten, reksa dana dapat menjadi sarana yang efektif untuk mencapai berbagai target keuangan di masa depan.",
        'icon' => 'users',
        'badge' => 'REKOMENDASI'
    ],
    'Obligasi' => [
        'description' => "Obligasi adalah surat utang yang diterbitkan oleh pemerintah maupun perusahaan sebagai sarana untuk memperoleh pendanaan dari masyarakat atau investor. Ketika membeli obligasi, investor pada dasarnya memberikan pinjaman kepada penerbit obligasi dan akan menerima pembayaran bunga secara berkala yang disebut kupon. Pada saat jatuh tempo, penerbit akan mengembalikan pokok investasi kepada investor sesuai nilai yang telah disepakati. Karena memiliki aliran pendapatan yang relatif stabil, obligasi sering dianggap sebagai instrumen investasi yang lebih konservatif dibandingkan saham.\n\nInvestasi obligasi memiliki beberapa keunggulan yang membuatnya menarik bagi berbagai kalangan investor. Salah satunya adalah adanya pendapatan tetap berupa kupon yang dibayarkan secara berkala. Selain itu, obligasi pemerintah umumnya memiliki tingkat risiko yang rendah karena dijamin oleh negara. Obligasi juga dapat menjadi alat diversifikasi portofolio yang efektif karena pergerakan nilainya tidak selalu sejalan dengan saham. Dengan demikian, keberadaan obligasi dalam portofolio investasi dapat membantu menjaga stabilitas nilai aset secara keseluruhan.\n\nWalaupun tergolong lebih aman dibandingkan saham, obligasi tetap memiliki sejumlah risiko yang perlu diperhatikan. Risiko suku bunga dapat menyebabkan harga obligasi turun ketika tingkat suku bunga pasar meningkat. Selain itu, terdapat risiko gagal bayar apabila penerbit obligasi mengalami kesulitan keuangan dan tidak mampu memenuhi kewajibannya. Oleh karena itu, investor perlu mempertimbangkan kualitas penerbit, peringkat kredit obligasi, serta kondisi ekonomi sebelum memutuskan untuk berinvestasi pada instrumen ini.",
        'icon' => 'file-text',
        'badge' => 'STABIL'
    ],
    'Properti' => [
        'description' => "Investasi properti merupakan kegiatan menanamkan modal dalam bentuk aset fisik seperti rumah, apartemen, ruko, tanah, maupun bangunan komersial dengan tujuan memperoleh keuntungan di masa depan. Keuntungan tersebut dapat berasal dari kenaikan nilai aset seiring waktu maupun dari pendapatan sewa yang diperoleh secara rutin. Properti sering dianggap sebagai salah satu bentuk investasi yang memiliki nilai nyata dan cenderung mampu mempertahankan nilainya dalam jangka panjang, terutama di wilayah yang mengalami pertumbuhan ekonomi dan peningkatan jumlah penduduk.\n\nSalah satu alasan banyak orang memilih investasi properti adalah potensinya untuk menghasilkan pendapatan pasif melalui penyewaan aset. Selain itu, nilai properti umumnya mengalami kenaikan dari tahun ke tahun karena faktor inflasi, perkembangan infrastruktur, dan meningkatnya permintaan pasar. Properti juga dapat digunakan sebagai jaminan untuk memperoleh pembiayaan dari lembaga keuangan. Dengan perencanaan yang baik, investasi properti dapat menjadi sumber kekayaan jangka panjang yang memberikan manfaat finansial yang berkelanjutan.\n\nNamun demikian, investasi properti membutuhkan modal awal yang relatif besar dibandingkan banyak instrumen investasi lainnya. Selain itu, investor harus mempertimbangkan biaya tambahan seperti perawatan bangunan, pajak, renovasi, dan biaya administrasi lainnya. Likuiditas properti juga tergolong rendah karena proses penjualan aset membutuhkan waktu yang tidak singkat. Oleh karena itu, calon investor perlu melakukan analisis lokasi, potensi perkembangan wilayah, dan kondisi pasar sebelum memutuskan untuk membeli properti sebagai instrumen investasi.",
        'icon' => 'home',
        'badge' => 'JANGKA PANJANG'
    ],
    'Emas' => [
        'description' => "Emas merupakan salah satu instrumen investasi yang telah digunakan selama berabad-abad sebagai penyimpan nilai dan alat lindung terhadap inflasi. Investasi emas dapat dilakukan dalam bentuk emas batangan, koin emas, maupun emas digital yang saat ini semakin mudah diakses melalui berbagai platform keuangan. Emas memiliki karakteristik unik karena nilainya cenderung stabil dalam jangka panjang dan sering menjadi pilihan investor ketika kondisi ekonomi global mengalami ketidakpastian.\n\nKeunggulan utama investasi emas adalah tingkat likuiditas yang tinggi dan kemudahan dalam proses jual beli. Selain itu, emas tidak bergantung pada kinerja perusahaan tertentu sehingga risikonya relatif lebih rendah dibandingkan saham. Dalam kondisi inflasi tinggi atau gejolak ekonomi, harga emas sering mengalami kenaikan karena banyak investor mengalihkan dana mereka ke aset yang dianggap lebih aman. Oleh karena itu, emas sering dimanfaatkan sebagai instrumen diversifikasi untuk menjaga keseimbangan portofolio investasi.\n\nMeskipun memiliki tingkat keamanan yang cukup baik, emas juga memiliki beberapa keterbatasan. Emas tidak memberikan pendapatan pasif seperti dividen saham atau kupon obligasi sehingga keuntungan hanya diperoleh dari kenaikan harga jual. Selain itu, harga emas tetap dapat mengalami fluktuasi akibat perubahan kondisi pasar global, nilai tukar mata uang, dan kebijakan ekonomi internasional. Oleh sebab itu, investasi emas lebih cocok digunakan sebagai sarana penyimpanan nilai dan perlindungan aset dalam jangka panjang.",
        'icon' => 'award',
        'badge' => 'TAHAN INFLASI'
    ],
    'Crypto' => [
        'description' => "Cryptocurrency atau aset kripto adalah mata uang digital yang menggunakan teknologi blockchain untuk mencatat dan mengamankan seluruh transaksi yang terjadi dalam jaringan. Berbeda dengan mata uang konvensional yang dikendalikan oleh bank sentral, sebagian besar aset kripto bersifat terdesentralisasi sehingga tidak berada di bawah kendali satu lembaga tertentu. Beberapa contoh aset kripto yang populer antara lain Bitcoin, Ethereum, dan berbagai jenis token digital lainnya yang digunakan untuk berbagai tujuan dalam ekosistem blockchain.\n\nInvestasi kripto menarik perhatian banyak investor karena potensi keuntungan yang sangat besar dalam waktu relatif singkat. Perkembangan teknologi blockchain juga membuka peluang inovasi di berbagai sektor seperti keuangan, logistik, kesehatan, hingga industri kreatif. Selain itu, transaksi aset kripto dapat dilakukan secara global selama dua puluh empat jam setiap hari tanpa batasan jam operasional seperti pasar saham tradisional. Faktor-faktor tersebut membuat aset kripto menjadi salah satu instrumen investasi yang berkembang pesat dalam beberapa tahun terakhir.\n\nDi balik potensi keuntungannya yang tinggi, aset kripto juga memiliki risiko yang sangat besar. Harga aset kripto dapat mengalami kenaikan maupun penurunan yang ekstrem dalam waktu singkat akibat sentimen pasar, regulasi pemerintah, maupun perkembangan teknologi. Risiko keamanan seperti peretasan platform perdagangan dan kehilangan akses dompet digital juga perlu diperhatikan. Oleh karena itu, investor disarankan untuk memahami cara kerja aset kripto, melakukan riset yang mendalam, serta hanya menginvestasikan dana yang siap menghadapi risiko tinggi sebelum berpartisipasi dalam pasar kripto.",
        'icon' => 'bitcoin',
        'badge' => 'RISIKO TINGGI'
    ]
];

foreach ($data as $name => $fields) {
    $cat = InvestmentCategory::where('name', $name)->first();
    if (!$cat) {
        $cat = new InvestmentCategory();
        $cat->name = $name;
        $cat->icon = $fields['icon'];
        $cat->badge = $fields['badge'];
    }
    $cat->description = $fields['description'];
    $cat->save();
}

echo "Berhasil update 7 kategori!\n";
